BLE_SUCCESS = 0

-- spp cmds
SET_ADV_INTERVAL						=0x01
SET_ADV_DATA							=0x02
ENABLE_ADV								=0x0A
SEND_DATA								=0x0B
GET_MOD_BUFF_NUM						=0x0C
SET_ADV_TYPE							=0x0D
SET_ADV_DIRECT_ADDR						=0x0E
ADD_WHITE_LST_ENTRY						=0x0F
DEL_WHITE_LST_ENTRY						=0x10
RST_WHITE_LST							=0x11
SET_FILTER_POLICY						=0x12
SET_DEVICE_NAME							=0x13
GET_CONN_PARAS							=0x14
SET_CONN_PARAS							=0x15
GET_MOD_CUR_STATE						=0x16
TERM_CONN								=0x17
RSTART_MOD								=0x18
ENABLE_MAC_BINDING						=0x19
ADD2_MAC_BINDING_TBL					=0x1a
DEL_F_MAC_BINDING_TBL					=0x1b
SET_PASSIVE_SCAN						=0x1c
